title: "Yuhang Lu"
description: "Ph.D. Student at HKU MMLab"
url: "https://yuhanglu2000.github.io"
baseurl: ""
repository: "yuhanglu2000/yuhanglu2000.github.io"
lang: "en"
timezone: Asia/Hong_Kong

author:
  name: "Yuhang Lu"
  alt_name: "陆宇航"
  avatar: "/images/profile_photo.jpg"
  location: "Hong Kong SAR, China"
  email: "lu.yuhang@connect.hku.hk"
  googlescholar: "https://scholar.google.com/citations?user=HiwDOksAAAAJ"
  github: "yuhanglu2000"
  twitter: "yuhang_L"

google_analytics_id:
google_site_verification:
bing_site_verification:
baidu_site_verification:

include:
  - .htaccess
  - files

exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  ignore:
    envs: development
